// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace XXMountainBrigade.Migrations
{
    [DbContext(typeof(XXMBContext))]
    partial class XXMBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XXMountainBrigade.Models.Company", b =>
                {
                    b.Property<int>("CoyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoyId"));

                    b.Property<string>("CoyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CoyId");

                    b.ToTable("tblCompany");

                    b.HasData(
                        new
                        {
                            CoyId = 1,
                            CoyName = "Company A"
                        },
                        new
                        {
                            CoyId = 2,
                            CoyName = "Company B"
                        });
                });

            modelBuilder.Entity("XXMountainBrigade.Models.Personnel", b =>
                {
                    b.Property<int>("PersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersId"));

                    b.Property<int>("CoyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PersNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RankId")
                        .HasColumnType("int");

                    b.HasKey("PersId");

                    b.HasIndex("CoyId");

                    b.HasIndex("RankId");

                    b.ToTable("tblPersonnel");

                    b.HasData(
                        new
                        {
                            PersId = 1,
                            CoyId = 1,
                            DateOfBirth = new DateTime(1994, 12, 4, 14, 33, 57, 458, DateTimeKind.Local).AddTicks(2369),
                            FirstName = "John",
                            LastName = "Doe",
                            PermanentAddress = "123 Main St, City, Country",
                            PersNo = "P001",
                            RankId = 1
                        },
                        new
                        {
                            PersId = 2,
                            CoyId = 2,
                            DateOfBirth = new DateTime(1999, 12, 4, 14, 33, 57, 459, DateTimeKind.Local).AddTicks(3514),
                            FirstName = "Jane",
                            LastName = "Smith",
                            PermanentAddress = "456 Oak St, City, Country",
                            PersNo = "P002",
                            RankId = 2
                        },
                        new
                        {
                            PersId = 3,
                            CoyId = 1,
                            DateOfBirth = new DateTime(1996, 12, 4, 14, 33, 57, 459, DateTimeKind.Local).AddTicks(3528),
                            FirstName = "Michael",
                            LastName = "Johnson",
                            PermanentAddress = "789 Pine St, City, Country",
                            PersNo = "P003",
                            RankId = 1
                        },
                        new
                        {
                            PersId = 4,
                            CoyId = 2,
                            DateOfBirth = new DateTime(1992, 12, 4, 14, 33, 57, 459, DateTimeKind.Local).AddTicks(3581),
                            FirstName = "Emily",
                            LastName = "Williams",
                            PermanentAddress = "101 Maple St, City, Country",
                            PersNo = "P004",
                            RankId = 2
                        });
                });

            modelBuilder.Entity("XXMountainBrigade.Models.Rank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RankId"));

                    b.Property<string>("RanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RankId");

                    b.ToTable("tblRanks");

                    b.HasData(
                        new
                        {
                            RankId = 1,
                            RanName = "Private"
                        },
                        new
                        {
                            RankId = 2,
                            RanName = "Sergeant"
                        });
                });

            modelBuilder.Entity("XXMountainBrigade.Models.Personnel", b =>
                {
                    b.HasOne("XXMountainBrigade.Models.Company", "Company")
                        .WithMany("Personnel")
                        .HasForeignKey("CoyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XXMountainBrigade.Models.Rank", "Rank")
                        .WithMany("Personnel")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("XXMountainBrigade.Models.Company", b =>
                {
                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("XXMountainBrigade.Models.Rank", b =>
                {
                    b.Navigation("Personnel");
                });
#pragma warning restore 612, 618
        }
    }
}
