// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace XX_MountainBrigade.Migrations
{
    [DbContext(typeof(XXMBContext))]
    [Migration("20241205032450_phase1")]
    partial class phase1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XX_MountainBrigade.Models.Company", b =>
                {
                    b.Property<int>("CoyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoyId"));

                    b.Property<string>("CoyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CoyId");

                    b.ToTable("tblCompany");

                    b.HasData(
                        new
                        {
                            CoyId = 1,
                            CoyName = "A Coy"
                        },
                        new
                        {
                            CoyId = 2,
                            CoyName = "B Coy"
                        },
                        new
                        {
                            CoyId = 3,
                            CoyName = "C Coy"
                        });
                });

            modelBuilder.Entity("XX_MountainBrigade.Models.Personnel", b =>
                {
                    b.Property<int>("PersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersId"));

                    b.Property<int>("CoyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PersNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RankId")
                        .HasColumnType("int");

                    b.Property<int?>("RegimentId")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfPersonnel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersId");

                    b.HasIndex("CoyId");

                    b.HasIndex("RankId");

                    b.HasIndex("RegimentId");

                    b.ToTable("tblPersonnel");

                    b.HasData(
                        new
                        {
                            PersId = 1,
                            CoyId = 1,
                            DateOfBirth = new DateTime(1994, 12, 5, 8, 54, 49, 897, DateTimeKind.Local).AddTicks(543),
                            FirstName = "John",
                            LastName = "Doe",
                            PermanentAddress = "123 Main St, City, Country",
                            PersNo = "P001",
                            RankId = 1,
                            RegimentId = 1,
                            TypeOfPersonnel = "Regular"
                        },
                        new
                        {
                            PersId = 2,
                            CoyId = 2,
                            DateOfBirth = new DateTime(1999, 12, 5, 8, 54, 49, 898, DateTimeKind.Local).AddTicks(1705),
                            FirstName = "Jane",
                            LastName = "Smith",
                            PermanentAddress = "456 Oak St, City, Country",
                            PersNo = "P002",
                            RankId = 2,
                            RegimentId = 2,
                            TypeOfPersonnel = "Regular"
                        },
                        new
                        {
                            PersId = 3,
                            CoyId = 1,
                            DateOfBirth = new DateTime(1996, 12, 5, 8, 54, 49, 898, DateTimeKind.Local).AddTicks(1720),
                            FirstName = "Michael",
                            LastName = "Johnson",
                            PermanentAddress = "789 Pine St, City, Country",
                            PersNo = "P003",
                            RankId = 1,
                            RegimentId = 1,
                            TypeOfPersonnel = "Regular"
                        },
                        new
                        {
                            PersId = 4,
                            CoyId = 2,
                            DateOfBirth = new DateTime(1992, 12, 5, 8, 54, 49, 898, DateTimeKind.Local).AddTicks(1724),
                            FirstName = "Emily",
                            LastName = "Williams",
                            PermanentAddress = "101 Maple St, City, Country",
                            PersNo = "P004",
                            RankId = 2,
                            RegimentId = 2,
                            TypeOfPersonnel = "Regular"
                        });
                });

            modelBuilder.Entity("XX_MountainBrigade.Models.Rank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RankId"));

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RankId");

                    b.ToTable("tblRanks");

                    b.HasData(
                        new
                        {
                            RankId = 1,
                            RankName = "Gunner"
                        },
                        new
                        {
                            RankId = 2,
                            RankName = "Rfn"
                        },
                        new
                        {
                            RankId = 3,
                            RankName = "Sepoy"
                        },
                        new
                        {
                            RankId = 4,
                            RankName = "Ln Naik"
                        },
                        new
                        {
                            RankId = 5,
                            RankName = "Havildar"
                        },
                        new
                        {
                            RankId = 6,
                            RankName = "Sub Major"
                        });
                });

            modelBuilder.Entity("XX_MountainBrigade.Models.Regiment", b =>
                {
                    b.Property<int>("RegId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegId"));

                    b.Property<int>("CoyId")
                        .HasColumnType("int");

                    b.Property<string>("RegimentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RegId");

                    b.HasIndex("CoyId");

                    b.ToTable("tblRegiments");

                    b.HasData(
                        new
                        {
                            RegId = 1,
                            CoyId = 1,
                            RegimentName = "1st Mountain Regiment"
                        },
                        new
                        {
                            RegId = 2,
                            CoyId = 2,
                            RegimentName = "2nd Mountain Regiment"
                        },
                        new
                        {
                            RegId = 3,
                            CoyId = 3,
                            RegimentName = "3rd Mountain Regiment"
                        });
                });

            modelBuilder.Entity("XX_MountainBrigade.Models.Personnel", b =>
                {
                    b.HasOne("XX_MountainBrigade.Models.Company", "Company")
                        .WithMany("Personnel")
                        .HasForeignKey("CoyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("XX_MountainBrigade.Models.Rank", "Rank")
                        .WithMany("Personnel")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("XX_MountainBrigade.Models.Regiment", "Regiment")
                        .WithMany("Personnel")
                        .HasForeignKey("RegimentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Rank");

                    b.Navigation("Regiment");
                });

            modelBuilder.Entity("XX_MountainBrigade.Models.Regiment", b =>
                {
                    b.HasOne("XX_MountainBrigade.Models.Company", "Company")
                        .WithMany("Regiments")
                        .HasForeignKey("CoyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("XX_MountainBrigade.Models.Company", b =>
                {
                    b.Navigation("Personnel");

                    b.Navigation("Regiments");
                });

            modelBuilder.Entity("XX_MountainBrigade.Models.Rank", b =>
                {
                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("XX_MountainBrigade.Models.Regiment", b =>
                {
                    b.Navigation("Personnel");
                });
#pragma warning restore 612, 618
        }
    }
}
